name: webview_flutter_navfix
description: A Flutter plugin that provides a WebView widget on Android and iOS (Android Navigation Fix).
version: 0.3.3+1
author: KM Tong <kmtong@gmail.com>
homepage: https://github.com/kmtong/plugins/tree/navfix/packages/webview_flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=0.11.9 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.webviewflutter
    iosPrefix: FLT
    pluginClass: WebViewFlutterPlugin
